spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://eva2_spring:tIcrUkaZuSyapGoL@cluster-spring.xjzn5yb.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=cluster-spring
spring.data.mongodb.database=discografica-db
